services:
  nginx:
    image: nginx:1.25-alpine
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./staticfiles:/static:ro
      - ./media:/media:ro
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - app_network

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data
    env_file:
      - .env.prod
    ports:
      - "5432:5432"
    networks:
      - app_network

  web:
    build: .
    restart: unless-stopped
    volumes:
      - .:/app
      - ./staticfiles:/static
      - ./media:/media
      - ./templates/js:/static/js
    env_file:
      - .env.prod
    command: >
      sh -c "
        echo 'Waiting for PostgreSQL to start...'
        while ! nc -z db 5432; do
          sleep 1
        done
        echo 'PostgreSQL started'
        python manage.py collectstatic --noinput &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    #ports:
    #  - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network



volumes:
  postgres_data_v2:

networks:
  app_network:
    driver: bridge